-- ecommerce.sql
DROP TABLE IF EXISTS cart;

CREATE TABLE cart (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE cart ADD CONSTRAINT fk_product
FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE cart ADD CONSTRAINT fk_user
FOREIGN KEY (user_id) REFERENCES users(id);